### ISSUE TITLE
Print finish message after compile/bundle

### ISSUE THREAD

**Issue by Quelklef** [ursi/purs-nix#4]
After `purs-nix compile` or `purs-nix bundle`, print something like `✨ done ✨`

Useful for e.g. running `purs-nix bundle` on file change: without a done message, when the console stops outputting messages, I don't know if it's completed compilation or if I just need to wait a moment longer before seeing my compiler warnings

Currently I just add this message myself, but I figure it could be nice to have in purs-nix

Happy to implement if you're on board

**Comment by ursi** [comment]
I agree d32eb4e55a17765625115de334a8a9bbed4ca19e

**Comment by Quelklef** [comment]
Nice! :tada:
